version: "3.7"

services:
  init-db:
    image: "ghcr.io/patricioperezv/rathena-server-pec/rathena:f3c8c70c810788f774ec39bf1cd8570488182742"
    command: sh -c "cp -r /rathena/sql-files/* /db-migration/ && tail -f /dev/null"
    user: root
    volumes:
      - rathena_sql_files:/db-migration
    deploy:
      restart_policy:
        condition: none
  db:
    image: "mariadb:11"
    ports:
      - "3306:3306" # allow DB connections from host
    volumes:
      - "/data/AppData/rathena/db:/var/lib/mysql" # save database to local disk
      - rathena_sql_files:/docker-entrypoint-initdb.d # initialize db with sql files
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: rathena
      MARIADB_USER: rathena
      MARIADB_PASSWORD_FILE: /run/secrets/RATHENA_DB_PASSWORD
    secrets:
      - RATHENA_DB_PASSWORD
    depends_on:
      - init-db
  login:
    image: "ghcr.io/patricioperezv/rathena-server-pec/rathena:f3c8c70c810788f774ec39bf1cd8570488182742"
    #command: sh -c "/bin/gomplate -d db_password=/run/secrets/RATHENA_DB_PASSWORD -f /rathena/conf/import/inter_conf.txt && /bin/wait-for db:3306 -- /rathena/login-server"
    command: sh -c "/bin/gomplate -d db_password=/run/secrets/RATHENA_DB_PASSWORD -f /tmp/inter_conf.txt -o /rathena/conf/import/inter_conf.txt && tail -f /dev/null"
    ports:
      - "6900:6900" # login server
    init: true # helps with signal forwarding and process reaping
    secrets:
      - RATHENA_DB_PASSWORD
    tty: true
    stdin_open: true
    configs:
      - source: inter_config
        target: /tmp/inter_conf.txt
      - source: char_config
        target: /tmp/char_conf.txt
      - source: map_config
        target: /tmp/map_conf.txt
    depends_on:
      - db
  # char:
  #   image: "ghcr.io/patricioperezv/rathena-server-pec/rathena:f3c8c70c810788f774ec39bf1cd8570488182742"
  #   container_name: "rathena-char"
  #   command: sh -c "/bin/wait-for db:3306 -- /rathena/char-server"
  #   ports:
  #     - "6121:6121" # char server
  #   volumes:
  #     - "./asset/inter_conf.txt:/rathena/conf/import/inter_conf.txt" # load db connection
  #     - "./asset/char_conf.txt:/rathena/conf/import/char_conf.txt" #localdev login-char relation
  #     - "./asset/map_conf.txt:/rathena/conf/import/map_conf.txt" #localdev char-map relation
  #   init: true # helps with signal forwarding and process reaping
  #   tty: true
  #   stdin_open: true
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - login

  # map:
  #   image: "rathena:local"
  #   container_name: "rathena-map"
  #   command: sh -c "/bin/wait-for db:3306 -- /rathena/map-server"
  #   ports:
  #     - "5121:5121" # map server
  #   volumes:
  #     - "../..:/rathena" # mount git repo directory inside container
  #     - "./asset/inter_conf.txt:/rathena/conf/import/inter_conf.txt" # load db connection
  #     - "./asset/char_conf.txt:/rathena/conf/import/char_conf.txt" #localdev login-char relation
  #     - "./asset/map_conf.txt:/rathena/conf/import/map_conf.txt" #localdev char-map relation
  #   init: true # helps with signal forwarding and process reaping
  #   tty: true
  #   stdin_open: true
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - char

volumes:
  rathena_sql_files:

secrets:
  RATHENA_DB_PASSWORD:
    external: true

configs:
  inter_config:
    file: config/inter.conf
  char_config:
    file: config/char.conf
  map_config:
    file: config/map.conf
