name: Build and Push Docker Image to GHCR

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Fetch latest revision from rathena/rathena
      run: |
        LATEST_REVISION=$(git ls-remote https://github.com/rathena/rathena.git refs/heads/master | awk '{print $1}')
        echo "LATEST_REVISION=$LATEST_REVISION" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and push Docker image
      run: |
        docker build --build-arg REVISION=${{ env.LATEST_REVISION }} -t ghcr.io/${{ github.repository }}/rathena:latest .
        docker push ghcr.io/${{ github.repository }}/rathena:latest
