name: Build and Push Docker Image to GHCR

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Fetch latest revision from rathena/rathena
      run: |
        LATEST_REVISION=$(git ls-remote https://github.com/rathena/rathena.git refs/heads/master | awk '{print $1}')
        echo "LATEST_REVISION=$LATEST_REVISION" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        build-args: REVISION=${{ env.LATEST_REVISION }}
        push: true
        tags: ghcr.io/${{ github.repository }}/rathena:${{ env.LATEST_REVISION }},ghcr.io/${{ github.repository }}/rathena:latest
  build-fluxcp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Fetch latest revision from rathena/fluxcp
      run: |
        LATEST_REVISION=$(git ls-remote https://github.com/rathena/FluxCP.git refs/heads/master | awk '{print $1}')
        echo "LATEST_REVISION=$LATEST_REVISION" >> $GITHUB_ENV
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        build-args: REVISION=${{ env.LATEST_REVISION }}
        push: true
        tags: ghcr.io/${{ github.repository }}/fluxcp:${{ env.LATEST_REVISION }},ghcr.io/${{ github.repository }}/fluxcp:latest
